using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Macaron.FluentEnum;

[Generator(LanguageNames.CSharp)]
public class EnumExtensionsGenerator : IIncrementalGenerator
{
    private const string AttributeSources =
        """
        // <auto-generated />
        using System;

        namespace Macaron.FluentEnum
        {
            [AttributeUsage(AttributeTargets.Enum)]
            internal class FluentAttribute : Attribute
            {
                public FluentAttribute(bool generateNegatedMembers = true)
                {
                    GenerateNegatedMembers = generateNegatedMembers;
                }

                public bool GenerateNegatedMembers { get; }
            }

            [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
            internal class FluentOfAttribute : Attribute
            {
                public FluentOfAttribute(Type enumType, bool generateNegatedMembers = true)
                {
                    EnumType = enumType;
                    GenerateNegatedMembers = generateNegatedMembers;
                }

                public Type EnumType { get; }

                public bool GenerateNegatedMembers { get; }
            }
        }

        """;

    private const string DefaultIndent = "    ";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource(
                hintName: "FluentAttribute.g.cs",
                sourceText: SourceText.From(text: AttributeSources, encoding: Encoding.UTF8)
            );
        });

        // FluentAttribute
        var enumValuesProvider = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: EnumContextFactory.FluentAttributeMetadataName,
                predicate: static (syntaxNode, _) => syntaxNode is EnumDeclarationSyntax,
                transform: static (generatorAttributeSyntaxContext, _) => EnumContextFactory.GetFluentContext(
                    generatorAttributeSyntaxContext
                )
            );

        context.RegisterSourceOutput(enumValuesProvider, static (sourceProductionContext, context) =>
        {
            var (enumContext, diagnostics) = context;

            foreach (var diagnostic in diagnostics)
            {
                sourceProductionContext.ReportDiagnostic(diagnostic);
            }

            if (enumContext != null)
            {
                SourceGenerationHelper.AddSource(
                    context: sourceProductionContext,
                    typeSymbol: enumContext.Symbol,
                    accessModifier: enumContext.AccessModifier,
                    lines: ExtensionMethodRenderer.Render(
                        methods: ExtensionMethodFactory.Create(enumContext),
                        indent: DefaultIndent
                    ),
                    indent: DefaultIndent
                );
            }
        });

        // FluentOfAttribute
        var fluentOfValuesProvider = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: EnumContextFactory.FluentOfAttributeMetadataName,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorAttributeSyntaxContext, _) => EnumContextFactory.GetFluentOfContext(
                    generatorAttributeSyntaxContext
                )
            );

        context.RegisterSourceOutput(fluentOfValuesProvider, static (sourceProductionContext, context) =>
        {
            var (fluentOfContext, diagnostics) = context;

            foreach (var diagnostic in diagnostics)
            {
                sourceProductionContext.ReportDiagnostic(diagnostic);
            }

            if (fluentOfContext != null)
            {
                var (classSymbol, enumContext) = fluentOfContext;
                var (methods, memberDiagnostics) = FluentOfMethodFilter.Filter(
                    classSymbol,
                    enumContext,
                    methods: ExtensionMethodFactory.Create(enumContext)
                );

                foreach (var diagnostic in memberDiagnostics)
                {
                    sourceProductionContext.ReportDiagnostic(diagnostic);
                }

                SourceGenerationHelper.AddSourceToPartialClass(
                    context: sourceProductionContext,
                    classSymbol: classSymbol,
                    targetTypeSymbol: enumContext.Symbol,
                    lines: ExtensionMethodRenderer.Render(methods, DefaultIndent),
                    indent: DefaultIndent
                );
            }
        });
    }
}
