using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Macaron.FluentEnum;

[Generator(LanguageNames.CSharp)]
public class FluentOfEnumExtensionsGenerator : IIncrementalGenerator
{
    #region Constants
    private const string AttributeSource =
        """
        // <auto-generated />
        using System;

        namespace Macaron.FluentEnum
        {
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
            internal class FluentOfAttribute : Attribute
            {
                public FluentOfAttribute(Type enumType, bool generateNegatedMembers = true)
                {
                    EnumType = enumType;
                    GenerateNegatedMembers = generateNegatedMembers;
                }

                public Type EnumType { get; }

                public bool GenerateNegatedMembers { get; }
            }
        }

        """;
    private const string FluentOfAttributeMetadataName = "Macaron.FluentEnum.FluentOfAttribute";
    #endregion

    #region IIncrementalGenerator Interface
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource(
                hintName: "FluentOfAttribute.g.cs",
                sourceText: SourceText.From(text: AttributeSource, encoding: Encoding.UTF8)
            );
        });

        var analysisResult = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: FluentOfAttributeMetadataName,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorAttributeSyntaxContext, _) => EnumContextFactory.GetFluentOfContext(
                    generatorAttributeSyntaxContext
                )
            )
            .Where(static result => result != null)
            .Select(static (result, _) => result!);
        var diagnosticProvider = analysisResult
            .Where(static result => result is AnalysisResult<FluentOfContext>.Failure)
            .SelectMany(static (result, _) => ((AnalysisResult<FluentOfContext>.Failure)result).Diagnostics);
        var fluentOfContextProvider = analysisResult
            .Where(static result => result is AnalysisResult<FluentOfContext>.Success)
            .Select(static (result, _) => ((AnalysisResult<FluentOfContext>.Success)result).Context)
            .WithComparer(FluentOfContextComparer.Instance);

        context.RegisterSourceOutput(diagnosticProvider, static (sourceProductionContext, diagnostic) =>
        {
            sourceProductionContext.ReportDiagnostic(diagnostic);
        });
        context.RegisterSourceOutput(fluentOfContextProvider, static (sourceProductionContext, fluentOfContext) =>
        {
            SourceGenerationHelper.AddSource(
                context: sourceProductionContext,
                extensionClassContext: fluentOfContext.ExtensionClassContext,
                hintName: fluentOfContext.EnumContext.TypeContext.HintName,
                methods: ExtensionMethodFactory.Create(fluentOfContext.EnumContext)
            );
        });
    }
    #endregion
}
