using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Macaron.FluentEnum;

[Generator(LanguageNames.CSharp)]
public class FluentOfEnumExtensionsGenerator : IIncrementalGenerator
{
    #region Constants
    private const string AttributeSource =
        """
        // <auto-generated />
        using System;

        namespace Macaron.FluentEnum
        {
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
            internal class FluentOfAttribute : Attribute
            {
                public FluentOfAttribute(Type enumType, bool generateNegatedMembers = true)
                {
                    EnumType = enumType;
                    GenerateNegatedMembers = generateNegatedMembers;
                }

                public Type EnumType { get; }

                public bool GenerateNegatedMembers { get; }
            }
        }

        """;
    private const string FluentOfAttributeMetadataName = "Macaron.FluentEnum.FluentOfAttribute";
    #endregion

    #region IIncrementalGenerator Interface
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource(
                hintName: "FluentOfAttribute.g.cs",
                sourceText: SourceText.From(text: AttributeSource, encoding: Encoding.UTF8)
            );
        });

        var analysisResult = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: FluentOfAttributeMetadataName,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorAttributeSyntaxContext, cancellationToken) => AnalysisModelFactory.GetFluentOfModel(
                    generatorAttributeSyntaxContext,
                    cancellationToken
                )
            )
            .Where(static result => result != null)
            .Select(static (result, _) => result!);
        var diagnosticProvider = analysisResult
            .Where(static result => result is AnalysisResult<FluentOfModel>.Failure)
            .SelectMany(static (result, _) => ((AnalysisResult<FluentOfModel>.Failure)result).Diagnostics);
        var fluentOfModelProvider = analysisResult
            .Where(static result => result is AnalysisResult<FluentOfModel>.Success)
            .Select(static (result, _) => ((AnalysisResult<FluentOfModel>.Success)result).Model)
            .WithComparer(FluentOfModelComparer.Instance);

        context.RegisterSourceOutput(diagnosticProvider, static (sourceProductionContext, diagnostic) =>
        {
            sourceProductionContext.ReportDiagnostic(diagnostic);
        });
        context.RegisterSourceOutput(fluentOfModelProvider, static (sourceProductionContext, fluentOfModel) =>
        {
            var cancellationToken = sourceProductionContext.CancellationToken;

            SourceGenerationHelper.AddSource(
                context: sourceProductionContext,
                extensionClassModel: fluentOfModel.ExtensionClass,
                hintName: fluentOfModel.Enum.Generation.HintName,
                methodModels: ExtensionMethodModelFactory.Create(fluentOfModel.Enum, cancellationToken),
                cancellationToken
            );
        });
    }
    #endregion
}
