using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Macaron.FluentEnum;

[Generator(LanguageNames.CSharp)]
public class FluentEnumExtensionsGenerator : IIncrementalGenerator
{
    #region Constants
    private const string AttributeSource =
        """
        // <auto-generated />
        using System;

        namespace Macaron.FluentEnum
        {
            [AttributeUsage(AttributeTargets.Enum)]
            internal class FluentAttribute : Attribute
            {
                public FluentAttribute(bool generateNegatedMembers = true)
                {
                    GenerateNegatedMembers = generateNegatedMembers;
                }

                public bool GenerateNegatedMembers { get; }
            }
        }

        """;
    private const string FluentAttributeMetadataName = "Macaron.FluentEnum.FluentAttribute";
    #endregion

    #region IIncrementalGenerator Interface
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource(
                hintName: "FluentAttribute.g.cs",
                sourceText: SourceText.From(text: AttributeSource, encoding: Encoding.UTF8)
            );
        });

        var analysisResultProvider = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: FluentAttributeMetadataName,
                predicate: static (syntaxNode, _) => syntaxNode is EnumDeclarationSyntax,
                transform: static (generatorAttributeSyntaxContext, _) => EnumContextFactory.GetEnumContext(
                    generatorAttributeSyntaxContext
                )
            )
            .WithComparer(new AnalysisResultComparer<EnumContext>(EnumContextComparer.Instance));

        context.RegisterSourceOutput(analysisResultProvider, static (sourceProductionContext, result) =>
        {
            switch (result)
            {
                case AnalysisResult<EnumContext>.Success success:
                {
                    foreach (var enumContext in success.Contexts)
                    {
                        SourceGenerationHelper.AddSource(
                            context: sourceProductionContext,
                            enumType: enumContext.TypeContext,
                            methods: ExtensionMethodFactory.Create(enumContext)
                        );

                    }

                    break;
                }
                case AnalysisResult<EnumContext>.Failure failure:
                {
                    foreach (var diagnostic in failure.Diagnostics)
                    {
                        sourceProductionContext.ReportDiagnostic(diagnostic);
                    }

                    break;
                }
            }
        });
    }
    #endregion
}
