using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Macaron.FluentEnum;

[Generator(LanguageNames.CSharp)]
public class FluentOfEnumExtensionsGenerator : IIncrementalGenerator
{
    #region Constants
    private const string AttributeSource =
        """
        // <auto-generated />
        using System;

        namespace Macaron.FluentEnum
        {
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
            internal class FluentOfAttribute : Attribute
            {
                public FluentOfAttribute(Type enumType, bool generateNegatedMembers = true)
                {
                    EnumType = enumType;
                    GenerateNegatedMembers = generateNegatedMembers;
                }

                public Type EnumType { get; }

                public bool GenerateNegatedMembers { get; }
            }
        }

        """;
    private const string FluentOfAttributeMetadataName = "Macaron.FluentEnum.FluentOfAttribute";
    #endregion

    #region IIncrementalGenerator Interface
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource(
                hintName: "FluentOfAttribute.g.cs",
                sourceText: SourceText.From(text: AttributeSource, encoding: Encoding.UTF8)
            );
        });

        var analysisResultProvider = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: FluentOfAttributeMetadataName,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (generatorAttributeSyntaxContext, _) => EnumContextFactory.GetFluentOfContext(
                    generatorAttributeSyntaxContext
                )
            )
            .Where(static result => result != null)
            .Select(static (result, _) => result!);

        context.RegisterSourceOutput(analysisResultProvider, static (sourceProductionContext, result) =>
        {
            switch (result)
            {
                case AnalysisResult<FluentOfContext>.Success { Context: { } context }:
                {
                    var (classSymbol, enumContext) = context;

                    SourceGenerationHelper.AddSourceToPartialClass(
                        context: sourceProductionContext,
                        classSymbol,
                        hintName: enumContext.TypeContext.HintName,
                        methods: ExtensionMethodFactory.Create(enumContext)
                    );

                    break;
                }
                case AnalysisResult<FluentOfContext>.Failure failure:
                {
                    foreach (var diagnostic in failure.Diagnostics)
                    {
                        sourceProductionContext.ReportDiagnostic(diagnostic);
                    }

                    break;
                }
            }
        });
    }
    #endregion
}
