using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Macaron.FluentEnum;

[Generator(LanguageNames.CSharp)]
public class FluentEnumExtensionsGenerator : IIncrementalGenerator
{
    private const string AttributeSource =
        """
        // <auto-generated />
        using System;

        namespace Macaron.FluentEnum
        {
            [AttributeUsage(AttributeTargets.Enum)]
            internal class FluentAttribute : Attribute
            {
                public FluentAttribute(bool generateNegatedMembers = true)
                {
                    GenerateNegatedMembers = generateNegatedMembers;
                }

                public bool GenerateNegatedMembers { get; }
            }
        }

        """;

    private const string DefaultIndent = "    ";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource(
                hintName: "FluentAttribute.g.cs",
                sourceText: SourceText.From(text: AttributeSource, encoding: Encoding.UTF8)
            );
        });

        var enumValuesProvider = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: EnumContextFactory.FluentAttributeMetadataName,
                predicate: static (syntaxNode, _) => syntaxNode is EnumDeclarationSyntax,
                transform: static (generatorAttributeSyntaxContext, _) => EnumContextFactory.GetFluentContext(
                    generatorAttributeSyntaxContext
                )
            );

        context.RegisterSourceOutput(enumValuesProvider, static (sourceProductionContext, context) =>
        {
            var (enumContext, diagnostics) = context;

            foreach (var diagnostic in diagnostics)
            {
                sourceProductionContext.ReportDiagnostic(diagnostic);
            }

            if (enumContext != null)
            {
                SourceGenerationHelper.AddSource(
                    context: sourceProductionContext,
                    typeSymbol: enumContext.Symbol,
                    accessModifier: enumContext.AccessModifier,
                    lines: ExtensionMethodRenderer.Render(
                        methods: ExtensionMethodFactory.Create(enumContext),
                        indent: DefaultIndent
                    ),
                    indent: DefaultIndent
                );
            }
        });
    }
}
