using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Macaron.FluentEnum;

[Generator(LanguageNames.CSharp)]
public class FluentEnumExtensionsGenerator : IIncrementalGenerator
{
    #region Constants
    private const string AttributeSource =
        """
        // <auto-generated />
        using System;

        namespace Macaron.FluentEnum
        {
            [AttributeUsage(AttributeTargets.Enum)]
            internal class FluentAttribute : Attribute
            {
                public FluentAttribute(bool generateNegatedMembers = true)
                {
                    GenerateNegatedMembers = generateNegatedMembers;
                }

                public bool GenerateNegatedMembers { get; }
            }
        }

        """;
    private const string FluentAttributeMetadataName = "Macaron.FluentEnum.FluentAttribute";
    #endregion

    #region IIncrementalGenerator Interface
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource(
                hintName: "FluentAttribute.g.cs",
                sourceText: SourceText.From(text: AttributeSource, encoding: Encoding.UTF8)
            );
        });

        var analysisResult = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: FluentAttributeMetadataName,
                predicate: static (syntaxNode, _) => syntaxNode is EnumDeclarationSyntax,
                transform: static (generatorAttributeSyntaxContext, _) => AnalysisModelFactory.GetEnumModel(
                    generatorAttributeSyntaxContext
                )
            )
            .Where(static result => result is not null)
            .Select(static (result, _) => result!);
        var diagnosticProvider = analysisResult
            .Where(static result => result is AnalysisResult<EnumModel>.Failure)
            .SelectMany(static (result, _) => ((AnalysisResult<EnumModel>.Failure)result).Diagnostics);
        var enumModelProvider = analysisResult
            .Where(static result => result is AnalysisResult<EnumModel>.Success)
            .Select(static (result, _) => ((AnalysisResult<EnumModel>.Success)result).Model)
            .WithComparer(EnumModelComparer.Instance);

        context.RegisterSourceOutput(diagnosticProvider, static (sourceProductionContext, diagnostic) =>
        {
            sourceProductionContext.ReportDiagnostic(diagnostic);
        });
        context.RegisterSourceOutput(enumModelProvider, static (sourceProductionContext, enumModel) =>
        {
            SourceGenerationHelper.AddSource(
                context: sourceProductionContext,
                extensionClassModel: enumModel.Generation.ExtensionClass,
                hintName: enumModel.Generation.HintName,
                methodModels: ExtensionMethodModelFactory.Create(enumModel)
            );
        });
    }
    #endregion
}
