using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Macaron.FluentEnum;

internal static class SourceGenerationHelper
{
    private const string Indent = "    ";

    public static void AddSource(
        SourceProductionContext context,
        ExtensionClassContext extensionClassContext,
        string hintName,
        ImmutableArray<GeneratedMethod> methods
    )
    {
        var lines = ExtensionMethodRenderer.Render(methods, Indent);

        if (lines.IsDefaultOrEmpty)
        {
            return;
        }

        var stringBuilder = CreateStringBuilderWithFileHeader();
        var hasNamespace = extensionClassContext.Namespace.Length > 0;

        if (hasNamespace)
        {
            stringBuilder.AppendLine($"namespace {extensionClassContext.Namespace}");
            stringBuilder.AppendLine("{");
        }

        var depthSpacerText = hasNamespace ? Indent : "";

        stringBuilder.AppendLine(
            $"{depthSpacerText}{extensionClassContext.AccessModifier} static partial class {extensionClassContext.ClassName}"
        );
        stringBuilder.AppendLine($"{depthSpacerText}{{");

        depthSpacerText += Indent;

        foreach (var line in lines)
        {
            stringBuilder.AppendLine($"{(line.Length > 0 ? depthSpacerText : "")}{line}");
        }

        depthSpacerText = depthSpacerText[..^Indent.Length];
        stringBuilder.AppendLine($"{depthSpacerText}}}");

        if (hasNamespace)
        {
            stringBuilder.AppendLine("}");
        }

        context.AddSource(
            hintName: hintName,
            sourceText: SourceText.From(stringBuilder.ToString(), Encoding.UTF8)
        );
    }

    private static StringBuilder CreateStringBuilderWithFileHeader()
    {
        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("// <auto-generated />");
        stringBuilder.AppendLine("#nullable enable");
        stringBuilder.AppendLine();

        return stringBuilder;
    }
}
