using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Macaron.FluentEnum;

internal static class SourceGenerationHelper
{
    public static void AddSource(
        SourceProductionContext context,
        INamedTypeSymbol typeSymbol,
        string accessModifier,
        ImmutableArray<string> lines,
        string indent
    )
    {
        if (lines.IsDefaultOrEmpty)
        {
            return;
        }

        var stringBuilder = CreateStringBuilderWithFileHeader();

        // begin namespace
        var hasNamespace = !typeSymbol.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace)
        {
            stringBuilder.AppendLine($"namespace {typeSymbol.ContainingNamespace.ToDisplayString()}");
            stringBuilder.AppendLine($"{{");
        }

        var depthSpacerText = hasNamespace ? indent : "";

        // get nestedTypes
        var nestedTypeNames = new List<string>();
        var parentType = typeSymbol.ContainingType;
        while (parentType != null)
        {
            nestedTypeNames.Add(GetTypeName(parentType));
            parentType = parentType.ContainingType;
        }

        nestedTypeNames.Reverse();
        nestedTypeNames.Add($"{GetTypeName(typeSymbol)}Extensions");

        // begin containingType
        stringBuilder.AppendLine($"{depthSpacerText}{accessModifier} static partial class {string.Join("_", nestedTypeNames)}");
        stringBuilder.AppendLine($"{depthSpacerText}{{");

        // write content
        depthSpacerText += indent;

        foreach (var line in lines)
        {
            stringBuilder.AppendLine($"{(line.Length > 0 ? depthSpacerText : "")}{line}");
        }

        depthSpacerText = depthSpacerText[..^indent.Length];

        // end containingType
        stringBuilder.AppendLine($"{depthSpacerText}}}");

        // end namespace
        if (hasNamespace)
        {
            stringBuilder.AppendLine($"}}");
        }

        context.AddSource(
            hintName: GetHintName(typeSymbol),
            sourceText: SourceText.From(stringBuilder.ToString(), Encoding.UTF8)
        );

        #region Local Functions
        static string GetTypeName(INamedTypeSymbol typeSymbol)
        {
            return $"{typeSymbol.Name}{(typeSymbol.Arity > 0 ? $"_{typeSymbol.Arity}" : "")}";
        }
        #endregion
    }

    public static void AddSourceToPartialClass(
        SourceProductionContext context,
        INamedTypeSymbol classSymbol,
        INamedTypeSymbol targetTypeSymbol,
        ImmutableArray<string> lines,
        string indent
    )
    {
        if (lines.IsDefaultOrEmpty)
        {
            return;
        }

        var stringBuilder = CreateStringBuilderWithFileHeader();
        var hasNamespace = !classSymbol.ContainingNamespace.IsGlobalNamespace;

        if (hasNamespace)
        {
            stringBuilder.AppendLine($"namespace {classSymbol.ContainingNamespace.ToDisplayString()}");
            stringBuilder.AppendLine("{");
        }

        var depthSpacerText = hasNamespace ? indent : "";
        var accessModifier = classSymbol.DeclaredAccessibility == Accessibility.Public
            ? "public"
            : "internal";
        var className = NamingHelpers.GetEscapedKeyword(classSymbol.Name);

        stringBuilder.AppendLine($"{depthSpacerText}{accessModifier} static partial class {className}");
        stringBuilder.AppendLine($"{depthSpacerText}{{");

        depthSpacerText += indent;

        foreach (var line in lines)
        {
            stringBuilder.AppendLine($"{(line.Length > 0 ? depthSpacerText : "")}{line}");
        }

        depthSpacerText = depthSpacerText[..^indent.Length];
        stringBuilder.AppendLine($"{depthSpacerText}}}");

        if (hasNamespace)
        {
            stringBuilder.AppendLine("}");
        }

        context.AddSource(
            hintName: GetFluentOfHintName(classSymbol, targetTypeSymbol),
            sourceText: SourceText.From(stringBuilder.ToString(), Encoding.UTF8)
        );
    }

    private static StringBuilder CreateStringBuilderWithFileHeader()
    {
        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("// <auto-generated />");
        stringBuilder.AppendLine("#nullable enable");
        stringBuilder.AppendLine();

        return stringBuilder;
    }

    private static string GetHintName(INamedTypeSymbol typeSymbol)
    {
        var assemblyName = typeSymbol.ContainingAssembly != null ? $"{typeSymbol.ContainingAssembly}," : "";
        var qualifiedName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return $"{typeSymbol.Name}_{typeSymbol.Arity}.{GetStableHash($"{assemblyName}, {qualifiedName}"):x8}.g.cs";
    }

    private static string GetFluentOfHintName(
        INamedTypeSymbol classSymbol,
        INamedTypeSymbol targetTypeSymbol
    )
    {
        var className = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var targetTypeName = targetTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return $"{classSymbol.Name}.{GetStableHash($"{className}, {targetTypeName}"):x8}.FluentOf.g.cs";
    }

    private static uint GetStableHash(string value)
    {
        const uint fnvPrime = 16777619;
        const uint offsetBasis = 2166136261;

        var bytes = Encoding.UTF8.GetBytes(value);
        uint hash = offsetBasis;

        foreach (var b in bytes)
        {
            hash ^= b;
            hash *= fnvPrime;
        }

        return hash;
    }
}
