using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Macaron.FluentEnum.Tests;

[TestFixture]
public class EnumExtensionsGeneratorTests
{
    private static void AssertGeneratedCode(
        string sourceCode,
        string expected,
        out ImmutableArray<Diagnostic> diagnostics
    )
    {
        (diagnostics, var generatedCode) = CompileAndGetResults(sourceCode);

        Assert.That(generatedCode.ReplaceLineEndings(), Is.EqualTo(expected.ReplaceLineEndings()));
    }

    private static void AssertGeneratedCode(string sourceCode, string expected)
    {
        var (_, generatedCode) = CompileAndGetResults(sourceCode);

        Assert.That(generatedCode.ReplaceLineEndings(), Is.EqualTo(expected.ReplaceLineEndings()));
    }

    private static (ImmutableArray<Diagnostic> diagnostics, string generatedCode) CompileAndGetResults(string sourceCode)
    {
        var references = AppDomain
            .CurrentDomain
            .GetAssemblies()
            .Where(assembly => !assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>()
            .ToImmutableArray();

        var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
        var compilation = CSharpCompilation.Create(
            assemblyName: "Macaron.PropertyAccessor.Tests",
            syntaxTrees: [syntaxTree],
            references: references,
            options: new CSharpCompilationOptions(
                outputKind: OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );

        var generator = new EnumExtensionsGenerator();
        var driver = CSharpGeneratorDriver
            .Create(generator)
            .RunGeneratorsAndUpdateCompilation(
                compilation,
                out var outputCompilation,
                out var generatorDiagnostics
            );

        var result = driver.GetRunResult().Results.Single();
        var generatedCode = string.Join(
            Environment.NewLine,
            result.GeneratedSources
                .Where(static generatedSource => generatedSource.HintName != "FluentAttribute.g.cs")
                .Select(static generatedSource => generatedSource.SourceText.ToString())
        );

        var allDiagnostics = outputCompilation.GetDiagnostics()
            .Concat(generatorDiagnostics)
            .ToImmutableArray();

        return (allDiagnostics, generatedCode);
    }

    [Test]
    public void Should_GenerateExtensions_When_HasFluentAttribute()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            [Fluent]
            public enum Foo
            {
                None,

                Bar,
                Baz,
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                public static partial class FooExtensions
                {
                    public static bool Is(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo == value;
                    }

                    public static bool IsNot(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo != value;
                    }

                    public static bool IsNone(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.None;
                    }

                    public static bool IsBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }

                    public static bool IsBaz(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.Baz;
                    }

                    public static bool IsNotNone(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo != global::Macaron.FluentEnum.Tests.Foo.None;
                    }

                    public static bool IsNotBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo != global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }

                    public static bool IsNotBaz(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo != global::Macaron.FluentEnum.Tests.Foo.Baz;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_NotGenerateIsNot_When_MemberAlreadyHasNotPrefix()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            [Fluent]
            public enum Foo
            {
                Bar,
                NotBar,
                NotBaz,
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                public static partial class FooExtensions
                {
                    public static bool Is(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo == value;
                    }

                    public static bool IsNot(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo != value;
                    }

                    public static bool IsBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }

                    public static bool IsNotBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.NotBar;
                    }

                    public static bool IsNotBaz(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.NotBaz;
                    }

                    public static bool IsBaz(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo != global::Macaron.FluentEnum.Tests.Foo.NotBaz;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateHasExtensions_When_HasFluentAttributeWithFlagsAttribute()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;

            namespace Macaron.FluentEnum.Tests;

            [Fluent]
            [Flags]
            public enum Foo
            {
                None = 0x00,

                Bar = 0x01,
                Baz = 0x02,
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                public static partial class FooExtensions
                {
                    public static bool Is(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo == value;
                    }

                    public static bool IsNot(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo != value;
                    }

                    public static bool IsNone(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.None;
                    }

                    public static bool IsBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }

                    public static bool IsBaz(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.Baz;
                    }

                    public static bool IsNotNone(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo != global::Macaron.FluentEnum.Tests.Foo.None;
                    }

                    public static bool IsNotBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo != global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }

                    public static bool IsNotBaz(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo != global::Macaron.FluentEnum.Tests.Foo.Baz;
                    }

                    public static bool Has(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return (foo & value) == value;
                    }

                    public static bool HasNot(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return (foo & value) != value;
                    }

                    public static bool HasBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return (foo & global::Macaron.FluentEnum.Tests.Foo.Bar) == global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }

                    public static bool HasBaz(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return (foo & global::Macaron.FluentEnum.Tests.Foo.Baz) == global::Macaron.FluentEnum.Tests.Foo.Baz;
                    }

                    public static bool HasNotBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return (foo & global::Macaron.FluentEnum.Tests.Foo.Bar) != global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }

                    public static bool HasNotBaz(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return (foo & global::Macaron.FluentEnum.Tests.Foo.Baz) != global::Macaron.FluentEnum.Tests.Foo.Baz;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateExtensions_When_HasFluentAttributeWithoutNamespace()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using Macaron.FluentEnum;

            [Fluent(generateNegatedMembers: false)]
            public enum Foo
            {
                None,

                Bar,
                Baz,
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            public static partial class FooExtensions
            {
                public static bool Is(this global::Foo foo, global::Foo value)
                {
                    return foo == value;
                }

                public static bool IsNot(this global::Foo foo, global::Foo value)
                {
                    return foo != value;
                }

                public static bool IsNone(this global::Foo foo)
                {
                    return foo == global::Foo.None;
                }

                public static bool IsBar(this global::Foo foo)
                {
                    return foo == global::Foo.Bar;
                }

                public static bool IsBaz(this global::Foo foo)
                {
                    return foo == global::Foo.Baz;
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateExtensionsCorrectly_When_HasFluentAttributeInNestedType()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            public class Foo
            {
                [Fluent(generateNegatedMembers: false)]
                public enum Bar
                {
                    None,

                    Baz,
                    Qux,
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                public static partial class Foo_BarExtensions
                {
                    public static bool Is(this global::Macaron.FluentEnum.Tests.Foo.Bar bar, global::Macaron.FluentEnum.Tests.Foo.Bar value)
                    {
                        return bar == value;
                    }

                    public static bool IsNot(this global::Macaron.FluentEnum.Tests.Foo.Bar bar, global::Macaron.FluentEnum.Tests.Foo.Bar value)
                    {
                        return bar != value;
                    }

                    public static bool IsNone(this global::Macaron.FluentEnum.Tests.Foo.Bar bar)
                    {
                        return bar == global::Macaron.FluentEnum.Tests.Foo.Bar.None;
                    }

                    public static bool IsBaz(this global::Macaron.FluentEnum.Tests.Foo.Bar bar)
                    {
                        return bar == global::Macaron.FluentEnum.Tests.Foo.Bar.Baz;
                    }

                    public static bool IsQux(this global::Macaron.FluentEnum.Tests.Foo.Bar bar)
                    {
                        return bar == global::Macaron.FluentEnum.Tests.Foo.Bar.Qux;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateExtensionsCorrectly_When_HasFluentAttributeInGenericNestedType()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            public interface IQux;

            public class Foo<T, TQux>
                where T : class
                where TQux : IQux
            {
                public class Bar<TBar>
                    where TBar : struct
                {
                    [Fluent(generateNegatedMembers: false)]
                    public enum Baz
                    {
                        None,
                    }
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                public static partial class Foo_2_Bar_1_BazExtensions
                {
                    public static bool Is<T, TQux, TBar>(this global::Macaron.FluentEnum.Tests.Foo<T, TQux>.Bar<TBar>.Baz baz, global::Macaron.FluentEnum.Tests.Foo<T, TQux>.Bar<TBar>.Baz value)
                        where T : class
                        where TQux : global::Macaron.FluentEnum.Tests.IQux
                        where TBar : struct
                    {
                        return baz == value;
                    }

                    public static bool IsNot<T, TQux, TBar>(this global::Macaron.FluentEnum.Tests.Foo<T, TQux>.Bar<TBar>.Baz baz, global::Macaron.FluentEnum.Tests.Foo<T, TQux>.Bar<TBar>.Baz value)
                        where T : class
                        where TQux : global::Macaron.FluentEnum.Tests.IQux
                        where TBar : struct
                    {
                        return baz != value;
                    }

                    public static bool IsNone<T, TQux, TBar>(this global::Macaron.FluentEnum.Tests.Foo<T, TQux>.Bar<TBar>.Baz baz)
                        where T : class
                        where TQux : global::Macaron.FluentEnum.Tests.IQux
                        where TBar : struct
                    {
                        return baz == global::Macaron.FluentEnum.Tests.Foo<T, TQux>.Bar<TBar>.Baz.None;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateExtensionsCorrectly_When_HasFluentAttributeInGenericNestedTypeWithoutNamespace()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using Macaron.FluentEnum;

            public interface IQux;

            public class Foo<T, TQux>
                where T : class
                where TQux : IQux
            {
                public class Bar<TBar>
                    where TBar : struct
                {
                    [Fluent]
                    public enum Baz
                    {
                        None,
                    }
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            public static partial class Foo_2_Bar_1_BazExtensions
            {
                public static bool Is<T, TQux, TBar>(this global::Foo<T, TQux>.Bar<TBar>.Baz baz, global::Foo<T, TQux>.Bar<TBar>.Baz value)
                    where T : class
                    where TQux : global::IQux
                    where TBar : struct
                {
                    return baz == value;
                }

                public static bool IsNot<T, TQux, TBar>(this global::Foo<T, TQux>.Bar<TBar>.Baz baz, global::Foo<T, TQux>.Bar<TBar>.Baz value)
                    where T : class
                    where TQux : global::IQux
                    where TBar : struct
                {
                    return baz != value;
                }

                public static bool IsNone<T, TQux, TBar>(this global::Foo<T, TQux>.Bar<TBar>.Baz baz)
                    where T : class
                    where TQux : global::IQux
                    where TBar : struct
                {
                    return baz == global::Foo<T, TQux>.Bar<TBar>.Baz.None;
                }

                public static bool IsNotNone<T, TQux, TBar>(this global::Foo<T, TQux>.Bar<TBar>.Baz baz)
                    where T : class
                    where TQux : global::IQux
                    where TBar : struct
                {
                    return baz != global::Foo<T, TQux>.Bar<TBar>.Baz.None;
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateExtensionsCorrectly_When_GenericNestedTypeHasDuplicatedTypeParameterNames()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            public interface IQux;

            public class Foo<T, TQux>
                where T : class, new()
                where TQux : IQux
            {
                public class Bar<T>
                    where T : struct
                {
                    [Fluent(generateNegatedMembers: false)]
                    public enum Baz
                    {
                        None,
                    }
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                public static partial class Foo_2_Bar_1_BazExtensions
                {
                    public static bool Is<T0, T1, T2>(this global::Macaron.FluentEnum.Tests.Foo<T0, T1>.Bar<T2>.Baz baz, global::Macaron.FluentEnum.Tests.Foo<T0, T1>.Bar<T2>.Baz value)
                        where T0 : class, new()
                        where T1 : global::Macaron.FluentEnum.Tests.IQux
                        where T2 : struct
                    {
                        return baz == value;
                    }

                    public static bool IsNot<T0, T1, T2>(this global::Macaron.FluentEnum.Tests.Foo<T0, T1>.Bar<T2>.Baz baz, global::Macaron.FluentEnum.Tests.Foo<T0, T1>.Bar<T2>.Baz value)
                        where T0 : class, new()
                        where T1 : global::Macaron.FluentEnum.Tests.IQux
                        where T2 : struct
                    {
                        return baz != value;
                    }

                    public static bool IsNone<T0, T1, T2>(this global::Macaron.FluentEnum.Tests.Foo<T0, T1>.Bar<T2>.Baz baz)
                        where T0 : class, new()
                        where T1 : global::Macaron.FluentEnum.Tests.IQux
                        where T2 : struct
                    {
                        return baz == global::Macaron.FluentEnum.Tests.Foo<T0, T1>.Bar<T2>.Baz.None;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateExtensionsCorrectly_When_GenericNestedTypeHasDuplicatedTypeParameterNamesWithoutNamespace()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using Macaron.FluentEnum;

            public interface IQux;

            public class Foo<T, TQux>
                where T : class, new()
                where TQux : IQux
            {
                public class Bar<T>
                    where T : struct
                {
                    [Fluent(generateNegatedMembers: false)]
                    public enum Baz
                    {
                        None,
                    }
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            public static partial class Foo_2_Bar_1_BazExtensions
            {
                public static bool Is<T0, T1, T2>(this global::Foo<T0, T1>.Bar<T2>.Baz baz, global::Foo<T0, T1>.Bar<T2>.Baz value)
                    where T0 : class, new()
                    where T1 : global::IQux
                    where T2 : struct
                {
                    return baz == value;
                }

                public static bool IsNot<T0, T1, T2>(this global::Foo<T0, T1>.Bar<T2>.Baz baz, global::Foo<T0, T1>.Bar<T2>.Baz value)
                    where T0 : class, new()
                    where T1 : global::IQux
                    where T2 : struct
                {
                    return baz != value;
                }

                public static bool IsNone<T0, T1, T2>(this global::Foo<T0, T1>.Bar<T2>.Baz baz)
                    where T0 : class, new()
                    where T1 : global::IQux
                    where T2 : struct
                {
                    return baz == global::Foo<T0, T1>.Bar<T2>.Baz.None;
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateInternalExtensions_When_AccessibilityIsInternal()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            internal class Foo
            {
                [Fluent(generateNegatedMembers: false)]
                public enum Bar
                {
                    None,

                    Baz,
                    Qux,
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                internal static partial class Foo_BarExtensions
                {
                    public static bool Is(this global::Macaron.FluentEnum.Tests.Foo.Bar bar, global::Macaron.FluentEnum.Tests.Foo.Bar value)
                    {
                        return bar == value;
                    }

                    public static bool IsNot(this global::Macaron.FluentEnum.Tests.Foo.Bar bar, global::Macaron.FluentEnum.Tests.Foo.Bar value)
                    {
                        return bar != value;
                    }

                    public static bool IsNone(this global::Macaron.FluentEnum.Tests.Foo.Bar bar)
                    {
                        return bar == global::Macaron.FluentEnum.Tests.Foo.Bar.None;
                    }

                    public static bool IsBaz(this global::Macaron.FluentEnum.Tests.Foo.Bar bar)
                    {
                        return bar == global::Macaron.FluentEnum.Tests.Foo.Bar.Baz;
                    }

                    public static bool IsQux(this global::Macaron.FluentEnum.Tests.Foo.Bar bar)
                    {
                        return bar == global::Macaron.FluentEnum.Tests.Foo.Bar.Qux;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_NotGenerateExtensions_When_AccessibilityIsNotPublicOrInternal()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            public partial class Foo
            {
                [Fluent]
                private enum Bar
                {
                    None,

                    Baz,
                    Qux,
                }
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0001"));
    }

    [Test]
    public void Should_GenerateExtensionsInAttributedClass_When_HasFluentOfAttribute()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                public static partial class CustomFooExtensions
                {
                    public static bool Is(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo == value;
                    }

                    public static bool IsNot(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo != value;
                    }

                    public static bool IsNone(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.None;
                    }

                    public static bool IsBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_NotGenerateEquivalentMethod_When_FluentOfClassAlreadyContainsMethod()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsBar(this Foo foo)
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Not.Contain("public static bool IsBar("));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0004"));
        });
    }

    [Test]
    public void Should_GenerateMethod_When_FluentOfClassContainsValidOverload()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsBar(this Foo foo, int value)
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool IsBar(this global::Macaron.FluentEnum.Tests.Foo foo)"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0004"));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_ClassMemberConflictsWithGeneratedMethod()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsBar => false;
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Not.Contain("public static bool IsBar("));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0004"));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_MethodContractConflictsWithGeneratedMethod()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static int IsBar(this Foo foo)
                {
                    return 0;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Not.Contain("public static bool IsBar("));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0004"));
        });
    }

    [Test]
    public void Should_GenerateClosedExtensions_When_FluentOfTargetsClosedNestedGenericEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : class, new()
            {
                public class Inner<U>
                    where U : struct
                {
                    public enum Foo
                    {
                        None,
                    }
                }
            }

            [FluentOf(typeof(Outer<object>.Inner<int>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(
                generatedCode,
                Does.Contain(
                    "public static bool Is(this global::Macaron.FluentEnum.Tests.Outer<object>.Inner<int>.Foo foo, global::Macaron.FluentEnum.Tests.Outer<object>.Inner<int>.Foo value)"
                )
            );
            Assert.That(generatedCode, Does.Not.Contain("public static bool Is<T"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id.StartsWith("MAFE")));
        });
    }

    [Test]
    public void Should_GenerateOpenExtensions_When_FluentOfTargetsOpenNestedGenericEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : class, new()
            {
                public class Inner<U>
                    where U : struct
                {
                    public enum Foo
                    {
                        None,
                    }
                }
            }

            [FluentOf(typeof(Outer<>.Inner<>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(
                generatedCode,
                Does.Contain(
                    "public static bool Is<T, U>(this global::Macaron.FluentEnum.Tests.Outer<T>.Inner<U>.Foo foo, global::Macaron.FluentEnum.Tests.Outer<T>.Inner<U>.Foo value)"
                )
            );
            Assert.That(generatedCode, Does.Contain("where T : class, new()"));
            Assert.That(generatedCode, Does.Contain("where U : struct"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id.StartsWith("MAFE")));
        });
    }

    [Test]
    public void Should_NotGenerateEquivalentGenericMethod_When_TypeParameterNamesDiffer()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : class, new()
            {
                public class Inner<U>
                    where U : struct
                {
                    public enum Foo
                    {
                        None,
                    }
                }
            }

            [FluentOf(typeof(Outer<>.Inner<>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsNone<TOuter, TInner>(
                    this Outer<TOuter>.Inner<TInner>.Foo foo
                )
                    where TOuter : class, new()
                    where TInner : struct
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Not.Contain("public static bool IsNone<"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0004"));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_FluentOfClassIsNotStaticPartial()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo))]
            public class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Is.Empty);
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0002"));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_FluentOfClassIsNested()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            public class Container
            {
                [FluentOf(typeof(Foo))]
                public static partial class CustomFooExtensions
                {
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Is.Empty);
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0002"));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_FluentOfTargetIsNotEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            [FluentOf(typeof(string))]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Is.Empty);
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0003"));
        });
    }

    [Test]
    public void Should_GenerateFlagExtensions_When_FluentOfTargetsFlagsEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            using System;

            namespace Macaron.FluentEnum.Tests;

            [Flags]
            public enum Foo
            {
                None = 0,
                Bar = 1,
                Baz = 2,
            }

            [FluentOf(typeof(Foo))]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool Has("));
            Assert.That(generatedCode, Does.Contain("public static bool HasNotBar("));
            Assert.That(generatedCode, Does.Not.Contain("public static bool HasNone("));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_GenericMethodConstraintsDiffer()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : class
            {
                public enum Foo
                {
                    None,
                }
            }

            [FluentOf(typeof(Outer<>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsNone<TActual>(this Outer<TActual>.Foo foo)
                    where TActual : class, new()
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Not.Contain("public static bool IsNone<"));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0004"));
        });
    }

    [Test]
    public void Should_GenerateOnce_When_FluentOfClassHasAnotherAttributedPartialDeclaration()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            using System;

            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }

            [Obsolete]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(
                generatedCode.Split(
                    "public static partial class CustomFooExtensions",
                    StringSplitOptions.None
                ),
                Has.Length.EqualTo(2)
            );
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_ExistingMethodHasOptionalParameter()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool Is(this Foo foo, Foo value = default)
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Not.Contain("public static bool Is("));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0004"));
        });
    }

    [Test]
    public void Should_EscapeKeywordClassName_When_FluentOfClassNameIsKeyword()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class @class
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static partial class @class"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        });
    }

    [Test]
    public void Should_GenerateValidSpecialConstraints_When_FluentOfTargetsOpenEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : unmanaged
            {
                public class Inner<U>
                    where U : notnull
                {
                    public enum Foo
                    {
                        None,
                    }
                }
            }

            [FluentOf(typeof(Outer<>.Inner<>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("where T : unmanaged"));
            Assert.That(generatedCode, Does.Not.Contain("where T : unmanaged, struct"));
            Assert.That(generatedCode, Does.Contain("where U : notnull"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        });
    }
}
