using Microsoft.CodeAnalysis;

using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using static System.Text.Encoding;
using static Macaron.FluentEnum.Tests.Helper;
using static Microsoft.CodeAnalysis.IncrementalGeneratorOutputKind;
using static Microsoft.CodeAnalysis.IncrementalStepRunReason;

namespace Macaron.FluentEnum.Tests;

[TestFixture]
public class FluentOfGeneratorTests
{
    [Test]
    public void Should_GenerateExtensionsInAttributedClass_When_HasFluentOfAttribute()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.FluentEnum.Tests
            {
                public static partial class CustomFooExtensions
                {
                    public static bool Is(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo == value;
                    }

                    public static bool IsNot(this global::Macaron.FluentEnum.Tests.Foo foo, global::Macaron.FluentEnum.Tests.Foo value)
                    {
                        return foo != value;
                    }

                    public static bool IsNone(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.None;
                    }

                    public static bool IsBar(this global::Macaron.FluentEnum.Tests.Foo foo)
                    {
                        return foo == global::Macaron.FluentEnum.Tests.Foo.Bar;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_ReportCompilerDiagnostic_When_FluentOfClassAlreadyContainsMethod()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsBar(this Foo foo)
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool IsBar("));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0111"));
        });
    }

    [Test]
    public void Should_GenerateMethod_When_FluentOfClassContainsValidOverload()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsBar(this Foo foo, int value)
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool IsBar(this global::Macaron.FluentEnum.Tests.Foo foo)"));
            Assert.That(
                diagnostics,
                Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            );
        });
    }

    [Test]
    public void Should_ReportCompilerDiagnostic_When_ClassMemberConflictsWithGeneratedMethod()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsBar => false;
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool IsBar("));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0102"));
        });
    }

    [Test]
    public void Should_ReportCompilerDiagnostic_When_MethodContractConflictsWithGeneratedMethod()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                Bar,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static int IsBar(this Foo foo)
                {
                    return 0;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool IsBar("));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0111"));
        });
    }

    [Test]
    public void Should_GenerateClosedExtensions_When_FluentOfTargetsClosedNestedGenericEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : class, new()
            {
                public class Inner<U>
                    where U : struct
                {
                    public enum Foo
                    {
                        None,
                    }
                }
            }

            [FluentOf(typeof(Outer<object>.Inner<int>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(
                generatedCode,
                Does.Contain(
                    "public static bool Is(this global::Macaron.FluentEnum.Tests.Outer<object>.Inner<int>.Foo foo, global::Macaron.FluentEnum.Tests.Outer<object>.Inner<int>.Foo value)"
                )
            );
            Assert.That(generatedCode, Does.Not.Contain("public static bool Is<T"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id.StartsWith("MAFE")));
        });
    }

    [Test]
    public void Should_GenerateOpenExtensions_When_FluentOfTargetsOpenNestedGenericEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : class, new()
            {
                public class Inner<U>
                    where U : struct
                {
                    public enum Foo
                    {
                        None,
                    }
                }
            }

            [FluentOf(typeof(Outer<>.Inner<>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(
                generatedCode,
                Does.Contain(
                    "public static bool Is<T, U>(this global::Macaron.FluentEnum.Tests.Outer<T>.Inner<U>.Foo foo, global::Macaron.FluentEnum.Tests.Outer<T>.Inner<U>.Foo value)"
                )
            );
            Assert.That(generatedCode, Does.Contain("where T : class, new()"));
            Assert.That(generatedCode, Does.Contain("where U : struct"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id.StartsWith("MAFE")));
        });
    }

    [Test]
    public void Should_ReportCompilerDiagnostic_When_EquivalentGenericMethodUsesDifferentTypeParameterNames()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : class, new()
            {
                public class Inner<U>
                    where U : struct
                {
                    public enum Foo
                    {
                        None,
                    }
                }
            }

            [FluentOf(typeof(Outer<>.Inner<>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsNone<TOuter, TInner>(
                    this Outer<TOuter>.Inner<TInner>.Foo foo
                )
                    where TOuter : class, new()
                    where TInner : struct
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool IsNone<"));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0111"));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_FluentOfClassIsNotStaticPartial()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo))]
            public class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Is.Empty);
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0002"));
        });
    }

    [Test]
    public void Should_GenerateOtherFluentOfSources_When_AnalysisFails()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo))]
            public static partial class ValidFooExtensions
            {
            }

            [FluentOf(typeof(Foo))]
            public class InvalidFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("static partial class ValidFooExtensions"));
            Assert.That(generatedCode, Does.Not.Contain("static partial class InvalidFooExtensions"));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0002"));
        });
    }

    [Test]
    public void Should_FailWithoutGeneratorDiagnostic_When_FluentOfTargetIsErrorType()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo))]
            public static partial class ValidFooExtensions
            {
            }

            [FluentOf(typeof(MissingEnum))]
            public static partial class InvalidFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("static partial class ValidFooExtensions"));
            Assert.That(generatedCode, Does.Not.Contain("static partial class InvalidFooExtensions"));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0246"));
            Assert.That(
                diagnostics,
                Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id.StartsWith("MAFE"))
            );
        });
    }

    [Test]
    public void Should_NotGenerateSource_When_FluentOfIsDuplicatedAcrossPartialDeclarations()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo))]
            public static partial class FooExtensions
            {
            }

            [FluentOf(typeof(Foo))]
            public static partial class FooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Is.Empty);
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0579"));
            Assert.That(
                diagnostics,
                Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id.StartsWith("MAFE"))
            );
        });
    }

    [Test]
    public void Should_GenerateOtherFluentOfSources_When_TargetEnumHasNoMembers()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            public enum Empty
            {
            }

            [FluentOf(typeof(Foo))]
            public static partial class FooExtensions
            {
            }

            [FluentOf(typeof(Empty))]
            public static partial class EmptyExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("static partial class FooExtensions"));
            Assert.That(generatedCode, Does.Not.Contain("static partial class EmptyExtensions"));
            Assert.That(
                diagnostics,
                Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            );
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_FluentOfClassIsNested()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            public class Container
            {
                [FluentOf(typeof(Foo))]
                public static partial class CustomFooExtensions
                {
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Is.Empty);
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0002"));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_FluentOfTargetIsNotEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            [FluentOf(typeof(string))]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Is.Empty);
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MAFE0003"));
        });
    }

    [Test]
    public void Should_ReportDiagnostic_When_FluentOfTargetHasFluentAttribute()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            [Fluent]
            public enum Foo
            {
                None,
            }

            public enum Bar
            {
                None,
            }

            [FluentOf(typeof(Foo))]
            public static partial class CustomFooExtensions
            {
            }

            [FluentOf(typeof(Bar))]
            public static partial class CustomBarExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("static partial class FooExtensions"));
            Assert.That(generatedCode, Does.Not.Contain("static partial class CustomFooExtensions"));
            Assert.That(generatedCode, Does.Contain("static partial class CustomBarExtensions"));
            Assert.That(
                diagnostics,
                Has.Some.Matches<Diagnostic>(diagnostic =>
                    diagnostic.Id == "MAFE0004"
                    && diagnostic.GetMessage()
                        == "FluentOf on class 'CustomFooExtensions' cannot reference enum 'Foo' because it already has Fluent."
                )
            );
        });
    }

    [Test]
    public void Should_GenerateFlagExtensions_When_FluentOfTargetsFlagsEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            using System;

            namespace Macaron.FluentEnum.Tests;

            [Flags]
            public enum Foo
            {
                None = 0,
                Bar = 1,
                Baz = 2,
            }

            [FluentOf(typeof(Foo))]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool Has("));
            Assert.That(generatedCode, Does.Contain("public static bool HasNotBar("));
            Assert.That(generatedCode, Does.Not.Contain("public static bool HasNone("));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        });
    }

    [Test]
    public void Should_ReportCompilerDiagnostic_When_GenericMethodConstraintsDiffer()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : class
            {
                public enum Foo
                {
                    None,
                }
            }

            [FluentOf(typeof(Outer<>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool IsNone<TActual>(this Outer<TActual>.Foo foo)
                    where TActual : class, new()
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool IsNone<"));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0111"));
        });
    }

    [Test]
    public void Should_GenerateOnce_When_FluentOfClassHasAnotherAttributedPartialDeclaration()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            using System;

            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }

            [Obsolete]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(
                generatedCode.Split(
                    "public static partial class CustomFooExtensions",
                    StringSplitOptions.None
                ),
                Has.Length.EqualTo(2)
            );
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        });
    }

    [Test]
    public void Should_ReportCompilerDiagnostic_When_ExistingMethodHasOptionalParameter()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
                public static bool Is(this Foo foo, Foo value = default)
                {
                    return false;
                }
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static bool Is("));
            Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0111"));
        });
    }

    [Test]
    public void Should_EscapeKeywordClassName_When_FluentOfClassNameIsKeyword()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo), generateNegatedMembers: false)]
            public static partial class @class
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("public static partial class @class"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        });
    }

    [Test]
    public void Should_GenerateValidSpecialConstraints_When_FluentOfTargetsOpenEnum()
    {
        var (diagnostics, generatedCode) = CompileAndGetResults(
            """
            namespace Macaron.FluentEnum.Tests;

            public class Outer<T>
                where T : unmanaged
            {
                public class Inner<U>
                    where U : notnull
                {
                    public enum Foo
                    {
                        None,
                    }
                }
            }

            [FluentOf(typeof(Outer<>.Inner<>.Foo), generateNegatedMembers: false)]
            public static partial class CustomFooExtensions
            {
            }
            """
        );

        Assert.Multiple(() =>
        {
            Assert.That(generatedCode, Does.Contain("where T : unmanaged"));
            Assert.That(generatedCode, Does.Not.Contain("where T : unmanaged, struct"));
            Assert.That(generatedCode, Does.Contain("where U : notnull"));
            Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        });
    }
    [Test]
    public void Should_ReuseSourceOutput_When_OnlyTriviaChanges()
    {
        const string sourceCode =
            """
            namespace Macaron.FluentEnum.Tests;

            public enum Foo
            {
                None,
            }

            [FluentOf(typeof(Foo))]
            public static partial class CustomFooExtensions
            {
            }
            """;
        var compilation = CreateCompilation(sourceCode);
        var syntaxTree = compilation.SyntaxTrees.Single();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [new FluentOfGenerator().AsSourceGenerator()],
            additionalTexts: [],
            parseOptions: (CSharpParseOptions)syntaxTree.Options,
            optionsProvider: null,
            driverOptions: new GeneratorDriverOptions(
                disabledOutputs: None,
                trackIncrementalGeneratorSteps: true
            )
        );

        driver = driver.RunGenerators(compilation);

        var updatedText = SourceText.From(
            text: sourceCode.Replace(
                "public static partial class CustomFooExtensions",
                "public static partial class CustomFooExtensions // trivia change"
            ),
            encoding: UTF8
        );
        var updatedSyntaxTree = syntaxTree.WithChangedText(updatedText);
        var updatedCompilation = compilation.ReplaceSyntaxTree(syntaxTree, updatedSyntaxTree);

        driver = driver.RunGenerators(updatedCompilation);

        var runResult = driver.GetRunResult().Results.Single();
        var generatedFluentOfSources = runResult
            .GeneratedSources
            .Where(static generatedSource => generatedSource.HintName != "FluentOfAttribute.g.cs")
            .ToImmutableArray();
        var sourceOutputs = runResult
            .TrackedOutputSteps
            .SelectMany(static step => step.Value)
            .SelectMany(static step => step.Outputs)
            .ToImmutableArray();

        Assert.That(generatedFluentOfSources, Has.Length.EqualTo(1));
        Assert.That(
            generatedFluentOfSources[0].SourceText.ToString(),
            Does.Contain("static partial class CustomFooExtensions")
        );
        Assert.That(sourceOutputs, Is.Not.Empty);
        Assert.That(
            sourceOutputs,
            Has.All.Matches<(object Value, IncrementalStepRunReason Reason)>(static output =>
                output.Reason == Cached
            )
        );
    }
}
